language: php

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2

install:
  composer self-update
  composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --coverage-text